apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-otel-dd-trace
  labels:
    app: python-otel-dd-trace
    # tags.datadoghq.com/env: production # Replace <env> with your environment (e.g., "production")
    # tags.datadoghq.com/service: python-app # Replace <service> with your service name
    # tags.datadoghq.com/version: "1.0.0" # Replace <version> with your application version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-otel-dd-trace
  template:
    metadata:
      labels:
        app: python-otel-dd-trace
        # tags.datadoghq.com/env: production # Replace <env> with your environment
        # tags.datadoghq.com/service: python-app-2 # Replace <service> with your service name
        # tags.datadoghq.com/version: "1.0.0" # Replace <version> with your application version
      #   # admission.datadoghq.com/enabled: "true"
      # annotations:
      #   admission.datadoghq.com/python-lib.version: v2.17.3
    spec:
      containers:
        - name: python-otel-dd-trace
          image: 104013952213.dkr.ecr.eu-north-1.amazonaws.com/aharon-flask-app:python-dd-dogstatsd-3
          ports:
            - containerPort: 5500
          env:
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_URL
              value: "http://$(NODE):8127"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: STATSD_PORT
              value: "8128"